[window]
width = 955
height = 600
fullscreen = false
high-dpi = false

[input.keyboard-primary]
left = 'Left'
right = 'Right'
fire = 'L'
jump = 'Up'
pickup = 'K'
crouch = 'Down'
slide = 'RightControl'

[input.keyboard-secondary]
left = 'A'
right = 'D'
fire = 'V'
jump = 'W'
pickup = 'C'
crouch = 'S'
slide = 'F'

[[input.gamepads]]
id = 0
fire = 'A'
jump = 'X'
pickup = 'B'
slide = 'Y'
