name: Build test

on:
  push:
    branches:
      - main

jobs:
  fmt:
    runs-on: windows-latest
    name: Build test
    steps:
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          target: i686-pc-windows-msvc

      - name: Create project and build
        shell: bash
        run: |
          cargo new --bin fishfight
          cd fishfight/
          curl https://raw.githubusercontent.com/fishfight/FishFight/main/Cargo.toml > Cargo.toml
          cargo build --target i686-pc-windows-msvc
