on:
  push:
    branches:
      - schema_validation_test
    paths:
      - "**.json"
  pull_request:
    paths:
      - "**.json"

name: Format validation check

jobs:
  json-validation:
    runs-on: ubuntu-latest
    name: Validate JSON files
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install ajv-cli
        run: npm install -g ajv-cli

      - name: Validate files
        shell: bash
        run: ./scripts/validate_json.sh
